#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schooly
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Etablissement")]
	public partial class EtablissementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbox(box instance);
    partial void Updatebox(box instance);
    partial void Deletebox(box instance);
    partial void Insertcasier(casier instance);
    partial void Updatecasier(casier instance);
    partial void Deletecasier(casier instance);
    partial void Insertdipot(dipot instance);
    partial void Updatedipot(dipot instance);
    partial void Deletedipot(dipot instance);
    partial void Insertdocument(document instance);
    partial void Updatedocument(document instance);
    partial void Deletedocument(document instance);
    partial void InsertInfoEtab(InfoEtab instance);
    partial void UpdateInfoEtab(InfoEtab instance);
    partial void DeleteInfoEtab(InfoEtab instance);
    partial void Insertkhizana(khizana instance);
    partial void Updatekhizana(khizana instance);
    partial void Deletekhizana(khizana instance);
    partial void Insertkism(kism instance);
    partial void Updatekism(kism instance);
    partial void Deletekism(kism instance);
    partial void Insertmaslaha(maslaha instance);
    partial void Updatemaslaha(maslaha instance);
    partial void Deletemaslaha(maslaha instance);
    partial void Insertmorasala(morasala instance);
    partial void Updatemorasala(morasala instance);
    partial void Deletemorasala(morasala instance);
    partial void Insertmorasala_export(morasala_export instance);
    partial void Updatemorasala_export(morasala_export instance);
    partial void Deletemorasala_export(morasala_export instance);
    partial void Insertmorasala_import(morasala_import instance);
    partial void Updatemorasala_import(morasala_import instance);
    partial void Deletemorasala_import(morasala_import instance);
    partial void Insertpathclasse(pathclasse instance);
    partial void Updatepathclasse(pathclasse instance);
    partial void Deletepathclasse(pathclasse instance);
    partial void Insertraf(raf instance);
    partial void Updateraf(raf instance);
    partial void Deleteraf(raf instance);
    partial void Insertraff(raff instance);
    partial void Updateraff(raff instance);
    partial void Deleteraff(raff instance);
    partial void Insertsaf_khizana(saf_khizana instance);
    partial void Updatesaf_khizana(saf_khizana instance);
    partial void Deletesaf_khizana(saf_khizana instance);
    #endregion
		
		public EtablissementDataContext() : 
				base(global::Schooly.Properties.Settings.Default.EtablissementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EtablissementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EtablissementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EtablissementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EtablissementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<box> boxes
		{
			get
			{
				return this.GetTable<box>();
			}
		}
		
		public System.Data.Linq.Table<casier> casiers
		{
			get
			{
				return this.GetTable<casier>();
			}
		}
		
		public System.Data.Linq.Table<dipot> dipots
		{
			get
			{
				return this.GetTable<dipot>();
			}
		}
		
		public System.Data.Linq.Table<document> documents
		{
			get
			{
				return this.GetTable<document>();
			}
		}
		
		public System.Data.Linq.Table<InfoEtab> InfoEtabs
		{
			get
			{
				return this.GetTable<InfoEtab>();
			}
		}
		
		public System.Data.Linq.Table<khizana> khizanas
		{
			get
			{
				return this.GetTable<khizana>();
			}
		}
		
		public System.Data.Linq.Table<kism> kisms
		{
			get
			{
				return this.GetTable<kism>();
			}
		}
		
		public System.Data.Linq.Table<maslaha> maslahas
		{
			get
			{
				return this.GetTable<maslaha>();
			}
		}
		
		public System.Data.Linq.Table<morasala> morasalas
		{
			get
			{
				return this.GetTable<morasala>();
			}
		}
		
		public System.Data.Linq.Table<morasala_export> morasala_exports
		{
			get
			{
				return this.GetTable<morasala_export>();
			}
		}
		
		public System.Data.Linq.Table<morasala_import> morasala_imports
		{
			get
			{
				return this.GetTable<morasala_import>();
			}
		}
		
		public System.Data.Linq.Table<pathclasse> pathclasses
		{
			get
			{
				return this.GetTable<pathclasse>();
			}
		}
		
		public System.Data.Linq.Table<raf> rafs
		{
			get
			{
				return this.GetTable<raf>();
			}
		}
		
		public System.Data.Linq.Table<raff> raffs
		{
			get
			{
				return this.GetTable<raff>();
			}
		}
		
		public System.Data.Linq.Table<saf_khizana> saf_khizanas
		{
			get
			{
				return this.GetTable<saf_khizana>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.box")]
	public partial class box : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id_box;
		
		private string _nom_box;
		
		private string _code_box;
		
		private string _raf_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_boxChanging(string value);
    partial void OnId_boxChanged();
    partial void Onnom_boxChanging(string value);
    partial void Onnom_boxChanged();
    partial void Oncode_boxChanging(string value);
    partial void Oncode_boxChanged();
    partial void Onraf_idChanging(string value);
    partial void Onraf_idChanged();
    #endregion
		
		public box()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_box", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_box
		{
			get
			{
				return this._Id_box;
			}
			set
			{
				if ((this._Id_box != value))
				{
					this.OnId_boxChanging(value);
					this.SendPropertyChanging();
					this._Id_box = value;
					this.SendPropertyChanged("Id_box");
					this.OnId_boxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_box", DbType="NVarChar(100)")]
		public string nom_box
		{
			get
			{
				return this._nom_box;
			}
			set
			{
				if ((this._nom_box != value))
				{
					this.Onnom_boxChanging(value);
					this.SendPropertyChanging();
					this._nom_box = value;
					this.SendPropertyChanged("nom_box");
					this.Onnom_boxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_box", DbType="NVarChar(50)")]
		public string code_box
		{
			get
			{
				return this._code_box;
			}
			set
			{
				if ((this._code_box != value))
				{
					this.Oncode_boxChanging(value);
					this.SendPropertyChanging();
					this._code_box = value;
					this.SendPropertyChanged("code_box");
					this.Oncode_boxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raf_id", DbType="NVarChar(50)")]
		public string raf_id
		{
			get
			{
				return this._raf_id;
			}
			set
			{
				if ((this._raf_id != value))
				{
					this.Onraf_idChanging(value);
					this.SendPropertyChanging();
					this._raf_id = value;
					this.SendPropertyChanged("raf_id");
					this.Onraf_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.casier")]
	public partial class casier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_cas;
		
		private string _cas_cas;
		
		private System.Nullable<int> _raf_id_cas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_casChanging(int value);
    partial void OnId_casChanged();
    partial void Oncas_casChanging(string value);
    partial void Oncas_casChanged();
    partial void Onraf_id_casChanging(System.Nullable<int> value);
    partial void Onraf_id_casChanged();
    #endregion
		
		public casier()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_cas", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_cas
		{
			get
			{
				return this._Id_cas;
			}
			set
			{
				if ((this._Id_cas != value))
				{
					this.OnId_casChanging(value);
					this.SendPropertyChanging();
					this._Id_cas = value;
					this.SendPropertyChanged("Id_cas");
					this.OnId_casChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cas_cas", DbType="NVarChar(100)")]
		public string cas_cas
		{
			get
			{
				return this._cas_cas;
			}
			set
			{
				if ((this._cas_cas != value))
				{
					this.Oncas_casChanging(value);
					this.SendPropertyChanging();
					this._cas_cas = value;
					this.SendPropertyChanged("cas_cas");
					this.Oncas_casChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raf_id_cas", DbType="Int")]
		public System.Nullable<int> raf_id_cas
		{
			get
			{
				return this._raf_id_cas;
			}
			set
			{
				if ((this._raf_id_cas != value))
				{
					this.Onraf_id_casChanging(value);
					this.SendPropertyChanging();
					this._raf_id_cas = value;
					this.SendPropertyChanged("raf_id_cas");
					this.Onraf_id_casChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dipot")]
	public partial class dipot : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id_dip;
		
		private string _nom_dip;
		
		private string _cod_dip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_dipChanging(string value);
    partial void OnId_dipChanged();
    partial void Onnom_dipChanging(string value);
    partial void Onnom_dipChanged();
    partial void Oncod_dipChanging(string value);
    partial void Oncod_dipChanged();
    #endregion
		
		public dipot()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_dip", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_dip
		{
			get
			{
				return this._Id_dip;
			}
			set
			{
				if ((this._Id_dip != value))
				{
					this.OnId_dipChanging(value);
					this.SendPropertyChanging();
					this._Id_dip = value;
					this.SendPropertyChanged("Id_dip");
					this.OnId_dipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_dip", DbType="NVarChar(100)")]
		public string nom_dip
		{
			get
			{
				return this._nom_dip;
			}
			set
			{
				if ((this._nom_dip != value))
				{
					this.Onnom_dipChanging(value);
					this.SendPropertyChanging();
					this._nom_dip = value;
					this.SendPropertyChanged("nom_dip");
					this.Onnom_dipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_dip", DbType="NVarChar(50)")]
		public string cod_dip
		{
			get
			{
				return this._cod_dip;
			}
			set
			{
				if ((this._cod_dip != value))
				{
					this.Oncod_dipChanging(value);
					this.SendPropertyChanging();
					this._cod_dip = value;
					this.SendPropertyChanged("cod_dip");
					this.Oncod_dipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.document")]
	public partial class document : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id_doc;
		
		private string _ref_doc;
		
		private string _obj_doc;
		
		private string _discr_doc;
		
		private string _typ_doc;
		
		private string _product_doc;
		
		private System.Nullable<System.DateTime> _dt_doc;
		
		private string _interesse_doc;
		
		private System.Nullable<bool> _distruction_doc;
		
		private string _dt_distruc_doc;
		
		private string _path_doc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_docChanging(string value);
    partial void OnId_docChanged();
    partial void Onref_docChanging(string value);
    partial void Onref_docChanged();
    partial void Onobj_docChanging(string value);
    partial void Onobj_docChanged();
    partial void Ondiscr_docChanging(string value);
    partial void Ondiscr_docChanged();
    partial void Ontyp_docChanging(string value);
    partial void Ontyp_docChanged();
    partial void Onproduct_docChanging(string value);
    partial void Onproduct_docChanged();
    partial void Ondt_docChanging(System.Nullable<System.DateTime> value);
    partial void Ondt_docChanged();
    partial void Oninteresse_docChanging(string value);
    partial void Oninteresse_docChanged();
    partial void Ondistruction_docChanging(System.Nullable<bool> value);
    partial void Ondistruction_docChanged();
    partial void Ondt_distruc_docChanging(string value);
    partial void Ondt_distruc_docChanged();
    partial void Onpath_docChanging(string value);
    partial void Onpath_docChanged();
    #endregion
		
		public document()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_doc", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_doc
		{
			get
			{
				return this._Id_doc;
			}
			set
			{
				if ((this._Id_doc != value))
				{
					this.OnId_docChanging(value);
					this.SendPropertyChanging();
					this._Id_doc = value;
					this.SendPropertyChanged("Id_doc");
					this.OnId_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ref_doc", DbType="NVarChar(50)")]
		public string ref_doc
		{
			get
			{
				return this._ref_doc;
			}
			set
			{
				if ((this._ref_doc != value))
				{
					this.Onref_docChanging(value);
					this.SendPropertyChanging();
					this._ref_doc = value;
					this.SendPropertyChanged("ref_doc");
					this.Onref_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obj_doc", DbType="NVarChar(200)")]
		public string obj_doc
		{
			get
			{
				return this._obj_doc;
			}
			set
			{
				if ((this._obj_doc != value))
				{
					this.Onobj_docChanging(value);
					this.SendPropertyChanging();
					this._obj_doc = value;
					this.SendPropertyChanged("obj_doc");
					this.Onobj_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discr_doc", DbType="NVarChar(300)")]
		public string discr_doc
		{
			get
			{
				return this._discr_doc;
			}
			set
			{
				if ((this._discr_doc != value))
				{
					this.Ondiscr_docChanging(value);
					this.SendPropertyChanging();
					this._discr_doc = value;
					this.SendPropertyChanged("discr_doc");
					this.Ondiscr_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typ_doc", DbType="NVarChar(50)")]
		public string typ_doc
		{
			get
			{
				return this._typ_doc;
			}
			set
			{
				if ((this._typ_doc != value))
				{
					this.Ontyp_docChanging(value);
					this.SendPropertyChanging();
					this._typ_doc = value;
					this.SendPropertyChanged("typ_doc");
					this.Ontyp_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_doc", DbType="NVarChar(50)")]
		public string product_doc
		{
			get
			{
				return this._product_doc;
			}
			set
			{
				if ((this._product_doc != value))
				{
					this.Onproduct_docChanging(value);
					this.SendPropertyChanging();
					this._product_doc = value;
					this.SendPropertyChanged("product_doc");
					this.Onproduct_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_doc", DbType="Date")]
		public System.Nullable<System.DateTime> dt_doc
		{
			get
			{
				return this._dt_doc;
			}
			set
			{
				if ((this._dt_doc != value))
				{
					this.Ondt_docChanging(value);
					this.SendPropertyChanging();
					this._dt_doc = value;
					this.SendPropertyChanged("dt_doc");
					this.Ondt_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interesse_doc", DbType="NVarChar(50)")]
		public string interesse_doc
		{
			get
			{
				return this._interesse_doc;
			}
			set
			{
				if ((this._interesse_doc != value))
				{
					this.Oninteresse_docChanging(value);
					this.SendPropertyChanging();
					this._interesse_doc = value;
					this.SendPropertyChanged("interesse_doc");
					this.Oninteresse_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distruction_doc", DbType="Bit")]
		public System.Nullable<bool> distruction_doc
		{
			get
			{
				return this._distruction_doc;
			}
			set
			{
				if ((this._distruction_doc != value))
				{
					this.Ondistruction_docChanging(value);
					this.SendPropertyChanging();
					this._distruction_doc = value;
					this.SendPropertyChanged("distruction_doc");
					this.Ondistruction_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_distruc_doc", DbType="NChar(10)")]
		public string dt_distruc_doc
		{
			get
			{
				return this._dt_distruc_doc;
			}
			set
			{
				if ((this._dt_distruc_doc != value))
				{
					this.Ondt_distruc_docChanging(value);
					this.SendPropertyChanging();
					this._dt_distruc_doc = value;
					this.SendPropertyChanged("dt_distruc_doc");
					this.Ondt_distruc_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_path_doc", DbType="NVarChar(300)")]
		public string path_doc
		{
			get
			{
				return this._path_doc;
			}
			set
			{
				if ((this._path_doc != value))
				{
					this.Onpath_docChanging(value);
					this.SendPropertyChanging();
					this._path_doc = value;
					this.SendPropertyChanged("path_doc");
					this.Onpath_docChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InfoEtab")]
	public partial class InfoEtab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _gresa_info;
		
		private string _etabNameAr_info;
		
		private string _etabNameFr_info;
		
		private string _comuneAr_info;
		
		private string _comuneFr_info;
		
		private string _directionAr_info;
		
		private string _directionFr_info;
		
		private string _academieAr_info;
		
		private string _academieFr_info;
		
		private string _phone_info;
		
		private string _adress_info;
		
		private string _email_info;
		
		private System.Nullable<int> _cardN_info;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongresa_infoChanging(string value);
    partial void Ongresa_infoChanged();
    partial void OnetabNameAr_infoChanging(string value);
    partial void OnetabNameAr_infoChanged();
    partial void OnetabNameFr_infoChanging(string value);
    partial void OnetabNameFr_infoChanged();
    partial void OncomuneAr_infoChanging(string value);
    partial void OncomuneAr_infoChanged();
    partial void OncomuneFr_infoChanging(string value);
    partial void OncomuneFr_infoChanged();
    partial void OndirectionAr_infoChanging(string value);
    partial void OndirectionAr_infoChanged();
    partial void OndirectionFr_infoChanging(string value);
    partial void OndirectionFr_infoChanged();
    partial void OnacademieAr_infoChanging(string value);
    partial void OnacademieAr_infoChanged();
    partial void OnacademieFr_infoChanging(string value);
    partial void OnacademieFr_infoChanged();
    partial void Onphone_infoChanging(string value);
    partial void Onphone_infoChanged();
    partial void Onadress_infoChanging(string value);
    partial void Onadress_infoChanged();
    partial void Onemail_infoChanging(string value);
    partial void Onemail_infoChanged();
    partial void OncardN_infoChanging(System.Nullable<int> value);
    partial void OncardN_infoChanged();
    #endregion
		
		public InfoEtab()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gresa_info", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string gresa_info
		{
			get
			{
				return this._gresa_info;
			}
			set
			{
				if ((this._gresa_info != value))
				{
					this.Ongresa_infoChanging(value);
					this.SendPropertyChanging();
					this._gresa_info = value;
					this.SendPropertyChanged("gresa_info");
					this.Ongresa_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etabNameAr_info", DbType="NVarChar(100)")]
		public string etabNameAr_info
		{
			get
			{
				return this._etabNameAr_info;
			}
			set
			{
				if ((this._etabNameAr_info != value))
				{
					this.OnetabNameAr_infoChanging(value);
					this.SendPropertyChanging();
					this._etabNameAr_info = value;
					this.SendPropertyChanged("etabNameAr_info");
					this.OnetabNameAr_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etabNameFr_info", DbType="NVarChar(100)")]
		public string etabNameFr_info
		{
			get
			{
				return this._etabNameFr_info;
			}
			set
			{
				if ((this._etabNameFr_info != value))
				{
					this.OnetabNameFr_infoChanging(value);
					this.SendPropertyChanging();
					this._etabNameFr_info = value;
					this.SendPropertyChanged("etabNameFr_info");
					this.OnetabNameFr_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comuneAr_info", DbType="NVarChar(100)")]
		public string comuneAr_info
		{
			get
			{
				return this._comuneAr_info;
			}
			set
			{
				if ((this._comuneAr_info != value))
				{
					this.OncomuneAr_infoChanging(value);
					this.SendPropertyChanging();
					this._comuneAr_info = value;
					this.SendPropertyChanged("comuneAr_info");
					this.OncomuneAr_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comuneFr_info", DbType="NVarChar(100)")]
		public string comuneFr_info
		{
			get
			{
				return this._comuneFr_info;
			}
			set
			{
				if ((this._comuneFr_info != value))
				{
					this.OncomuneFr_infoChanging(value);
					this.SendPropertyChanging();
					this._comuneFr_info = value;
					this.SendPropertyChanged("comuneFr_info");
					this.OncomuneFr_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_directionAr_info", DbType="NVarChar(100)")]
		public string directionAr_info
		{
			get
			{
				return this._directionAr_info;
			}
			set
			{
				if ((this._directionAr_info != value))
				{
					this.OndirectionAr_infoChanging(value);
					this.SendPropertyChanging();
					this._directionAr_info = value;
					this.SendPropertyChanged("directionAr_info");
					this.OndirectionAr_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_directionFr_info", DbType="NVarChar(100)")]
		public string directionFr_info
		{
			get
			{
				return this._directionFr_info;
			}
			set
			{
				if ((this._directionFr_info != value))
				{
					this.OndirectionFr_infoChanging(value);
					this.SendPropertyChanging();
					this._directionFr_info = value;
					this.SendPropertyChanged("directionFr_info");
					this.OndirectionFr_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_academieAr_info", DbType="NVarChar(100)")]
		public string academieAr_info
		{
			get
			{
				return this._academieAr_info;
			}
			set
			{
				if ((this._academieAr_info != value))
				{
					this.OnacademieAr_infoChanging(value);
					this.SendPropertyChanging();
					this._academieAr_info = value;
					this.SendPropertyChanged("academieAr_info");
					this.OnacademieAr_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_academieFr_info", DbType="NVarChar(100)")]
		public string academieFr_info
		{
			get
			{
				return this._academieFr_info;
			}
			set
			{
				if ((this._academieFr_info != value))
				{
					this.OnacademieFr_infoChanging(value);
					this.SendPropertyChanging();
					this._academieFr_info = value;
					this.SendPropertyChanged("academieFr_info");
					this.OnacademieFr_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_info", DbType="NVarChar(50)")]
		public string phone_info
		{
			get
			{
				return this._phone_info;
			}
			set
			{
				if ((this._phone_info != value))
				{
					this.Onphone_infoChanging(value);
					this.SendPropertyChanging();
					this._phone_info = value;
					this.SendPropertyChanged("phone_info");
					this.Onphone_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adress_info", DbType="NVarChar(300)")]
		public string adress_info
		{
			get
			{
				return this._adress_info;
			}
			set
			{
				if ((this._adress_info != value))
				{
					this.Onadress_infoChanging(value);
					this.SendPropertyChanging();
					this._adress_info = value;
					this.SendPropertyChanged("adress_info");
					this.Onadress_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_info", DbType="NVarChar(100)")]
		public string email_info
		{
			get
			{
				return this._email_info;
			}
			set
			{
				if ((this._email_info != value))
				{
					this.Onemail_infoChanging(value);
					this.SendPropertyChanging();
					this._email_info = value;
					this.SendPropertyChanged("email_info");
					this.Onemail_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cardN_info", DbType="Int")]
		public System.Nullable<int> cardN_info
		{
			get
			{
				return this._cardN_info;
			}
			set
			{
				if ((this._cardN_info != value))
				{
					this.OncardN_infoChanging(value);
					this.SendPropertyChanging();
					this._cardN_info = value;
					this.SendPropertyChanged("cardN_info");
					this.OncardN_infoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khizana")]
	public partial class khizana : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id_khiz;
		
		private string _nom_khiz;
		
		private string _code_khiz;
		
		private string _saf_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_khizChanging(string value);
    partial void OnId_khizChanged();
    partial void Onnom_khizChanging(string value);
    partial void Onnom_khizChanged();
    partial void Oncode_khizChanging(string value);
    partial void Oncode_khizChanged();
    partial void Onsaf_idChanging(string value);
    partial void Onsaf_idChanged();
    #endregion
		
		public khizana()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_khiz", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_khiz
		{
			get
			{
				return this._Id_khiz;
			}
			set
			{
				if ((this._Id_khiz != value))
				{
					this.OnId_khizChanging(value);
					this.SendPropertyChanging();
					this._Id_khiz = value;
					this.SendPropertyChanged("Id_khiz");
					this.OnId_khizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_khiz", DbType="NVarChar(100)")]
		public string nom_khiz
		{
			get
			{
				return this._nom_khiz;
			}
			set
			{
				if ((this._nom_khiz != value))
				{
					this.Onnom_khizChanging(value);
					this.SendPropertyChanging();
					this._nom_khiz = value;
					this.SendPropertyChanged("nom_khiz");
					this.Onnom_khizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_khiz", DbType="NVarChar(50)")]
		public string code_khiz
		{
			get
			{
				return this._code_khiz;
			}
			set
			{
				if ((this._code_khiz != value))
				{
					this.Oncode_khizChanging(value);
					this.SendPropertyChanging();
					this._code_khiz = value;
					this.SendPropertyChanged("code_khiz");
					this.Oncode_khizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saf_id", DbType="NVarChar(50)")]
		public string saf_id
		{
			get
			{
				return this._saf_id;
			}
			set
			{
				if ((this._saf_id != value))
				{
					this.Onsaf_idChanging(value);
					this.SendPropertyChanging();
					this._saf_id = value;
					this.SendPropertyChanged("saf_id");
					this.Onsaf_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kism")]
	public partial class kism : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_kism;
		
		private string _kism_kis;
		
		private System.Nullable<int> _mas_id_kis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_kismChanging(int value);
    partial void OnId_kismChanged();
    partial void Onkism_kisChanging(string value);
    partial void Onkism_kisChanged();
    partial void Onmas_id_kisChanging(System.Nullable<int> value);
    partial void Onmas_id_kisChanged();
    #endregion
		
		public kism()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_kism", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_kism
		{
			get
			{
				return this._Id_kism;
			}
			set
			{
				if ((this._Id_kism != value))
				{
					this.OnId_kismChanging(value);
					this.SendPropertyChanging();
					this._Id_kism = value;
					this.SendPropertyChanged("Id_kism");
					this.OnId_kismChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kism_kis", DbType="NVarChar(100)")]
		public string kism_kis
		{
			get
			{
				return this._kism_kis;
			}
			set
			{
				if ((this._kism_kis != value))
				{
					this.Onkism_kisChanging(value);
					this.SendPropertyChanging();
					this._kism_kis = value;
					this.SendPropertyChanged("kism_kis");
					this.Onkism_kisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mas_id_kis", DbType="Int")]
		public System.Nullable<int> mas_id_kis
		{
			get
			{
				return this._mas_id_kis;
			}
			set
			{
				if ((this._mas_id_kis != value))
				{
					this.Onmas_id_kisChanging(value);
					this.SendPropertyChanging();
					this._mas_id_kis = value;
					this.SendPropertyChanged("mas_id_kis");
					this.Onmas_id_kisChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.maslaha")]
	public partial class maslaha : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_mas;
		
		private string _mas_mas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_masChanging(int value);
    partial void OnId_masChanged();
    partial void Onmas_masChanging(string value);
    partial void Onmas_masChanged();
    #endregion
		
		public maslaha()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_mas", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_mas
		{
			get
			{
				return this._Id_mas;
			}
			set
			{
				if ((this._Id_mas != value))
				{
					this.OnId_masChanging(value);
					this.SendPropertyChanging();
					this._Id_mas = value;
					this.SendPropertyChanged("Id_mas");
					this.OnId_masChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mas_mas", DbType="NVarChar(100)")]
		public string mas_mas
		{
			get
			{
				return this._mas_mas;
			}
			set
			{
				if ((this._mas_mas != value))
				{
					this.Onmas_masChanging(value);
					this.SendPropertyChanging();
					this._mas_mas = value;
					this.SendPropertyChanged("mas_mas");
					this.Onmas_masChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.morasala")]
	public partial class morasala : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_cor;
		
		private string _subject_cor;
		
		private string _num_loc_cor;
		
		private string _num_ext_cor;
		
		private System.Nullable<System.DateTime> _dt_cor;
		
		private System.Nullable<System.DateTime> _dt_delai_cor;
		
		private System.Nullable<bool> _execute_cor;
		
		private string _jiha_cor;
		
		private string _source_cor;
		
		private System.Nullable<int> _maslaha_cor;
		
		private System.Nullable<int> @__9ism_cor;
		
		private string _type_arch_cor;
		
		private string _classeIn_dossier;
		
		private System.Nullable<int> _ref_doc_cor;
		
		private System.Nullable<int> _classIn_case_cor;
		
		private System.Nullable<int> _classIn_raf_cor;
		
		private string _locationPc_cor;
		
		private string _gresa_cor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_corChanging(int value);
    partial void OnId_corChanged();
    partial void Onsubject_corChanging(string value);
    partial void Onsubject_corChanged();
    partial void Onnum_loc_corChanging(string value);
    partial void Onnum_loc_corChanged();
    partial void Onnum_ext_corChanging(string value);
    partial void Onnum_ext_corChanged();
    partial void Ondt_corChanging(System.Nullable<System.DateTime> value);
    partial void Ondt_corChanged();
    partial void Ondt_delai_corChanging(System.Nullable<System.DateTime> value);
    partial void Ondt_delai_corChanged();
    partial void Onexecute_corChanging(System.Nullable<bool> value);
    partial void Onexecute_corChanged();
    partial void Onjiha_corChanging(string value);
    partial void Onjiha_corChanged();
    partial void Onsource_corChanging(string value);
    partial void Onsource_corChanged();
    partial void Onmaslaha_corChanging(System.Nullable<int> value);
    partial void Onmaslaha_corChanged();
    partial void On_9ism_corChanging(System.Nullable<int> value);
    partial void On_9ism_corChanged();
    partial void Ontype_arch_corChanging(string value);
    partial void Ontype_arch_corChanged();
    partial void OnclasseIn_dossierChanging(string value);
    partial void OnclasseIn_dossierChanged();
    partial void Onref_doc_corChanging(System.Nullable<int> value);
    partial void Onref_doc_corChanged();
    partial void OnclassIn_case_corChanging(System.Nullable<int> value);
    partial void OnclassIn_case_corChanged();
    partial void OnclassIn_raf_corChanging(System.Nullable<int> value);
    partial void OnclassIn_raf_corChanged();
    partial void OnlocationPc_corChanging(string value);
    partial void OnlocationPc_corChanged();
    partial void Ongresa_corChanging(string value);
    partial void Ongresa_corChanged();
    #endregion
		
		public morasala()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_cor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_cor
		{
			get
			{
				return this._Id_cor;
			}
			set
			{
				if ((this._Id_cor != value))
				{
					this.OnId_corChanging(value);
					this.SendPropertyChanging();
					this._Id_cor = value;
					this.SendPropertyChanged("Id_cor");
					this.OnId_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_cor", DbType="NVarChar(MAX)")]
		public string subject_cor
		{
			get
			{
				return this._subject_cor;
			}
			set
			{
				if ((this._subject_cor != value))
				{
					this.Onsubject_corChanging(value);
					this.SendPropertyChanging();
					this._subject_cor = value;
					this.SendPropertyChanged("subject_cor");
					this.Onsubject_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_loc_cor", DbType="NVarChar(50)")]
		public string num_loc_cor
		{
			get
			{
				return this._num_loc_cor;
			}
			set
			{
				if ((this._num_loc_cor != value))
				{
					this.Onnum_loc_corChanging(value);
					this.SendPropertyChanging();
					this._num_loc_cor = value;
					this.SendPropertyChanged("num_loc_cor");
					this.Onnum_loc_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_ext_cor", DbType="NVarChar(50)")]
		public string num_ext_cor
		{
			get
			{
				return this._num_ext_cor;
			}
			set
			{
				if ((this._num_ext_cor != value))
				{
					this.Onnum_ext_corChanging(value);
					this.SendPropertyChanging();
					this._num_ext_cor = value;
					this.SendPropertyChanged("num_ext_cor");
					this.Onnum_ext_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_cor", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_cor
		{
			get
			{
				return this._dt_cor;
			}
			set
			{
				if ((this._dt_cor != value))
				{
					this.Ondt_corChanging(value);
					this.SendPropertyChanging();
					this._dt_cor = value;
					this.SendPropertyChanged("dt_cor");
					this.Ondt_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_delai_cor", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_delai_cor
		{
			get
			{
				return this._dt_delai_cor;
			}
			set
			{
				if ((this._dt_delai_cor != value))
				{
					this.Ondt_delai_corChanging(value);
					this.SendPropertyChanging();
					this._dt_delai_cor = value;
					this.SendPropertyChanged("dt_delai_cor");
					this.Ondt_delai_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_execute_cor", DbType="Bit")]
		public System.Nullable<bool> execute_cor
		{
			get
			{
				return this._execute_cor;
			}
			set
			{
				if ((this._execute_cor != value))
				{
					this.Onexecute_corChanging(value);
					this.SendPropertyChanging();
					this._execute_cor = value;
					this.SendPropertyChanged("execute_cor");
					this.Onexecute_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jiha_cor", DbType="NVarChar(100)")]
		public string jiha_cor
		{
			get
			{
				return this._jiha_cor;
			}
			set
			{
				if ((this._jiha_cor != value))
				{
					this.Onjiha_corChanging(value);
					this.SendPropertyChanging();
					this._jiha_cor = value;
					this.SendPropertyChanged("jiha_cor");
					this.Onjiha_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_cor", DbType="NVarChar(50)")]
		public string source_cor
		{
			get
			{
				return this._source_cor;
			}
			set
			{
				if ((this._source_cor != value))
				{
					this.Onsource_corChanging(value);
					this.SendPropertyChanging();
					this._source_cor = value;
					this.SendPropertyChanged("source_cor");
					this.Onsource_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maslaha_cor", DbType="Int")]
		public System.Nullable<int> maslaha_cor
		{
			get
			{
				return this._maslaha_cor;
			}
			set
			{
				if ((this._maslaha_cor != value))
				{
					this.Onmaslaha_corChanging(value);
					this.SendPropertyChanging();
					this._maslaha_cor = value;
					this.SendPropertyChanged("maslaha_cor");
					this.Onmaslaha_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[9ism_cor]", Storage="__9ism_cor", DbType="Int")]
		public System.Nullable<int> _9ism_cor
		{
			get
			{
				return this.@__9ism_cor;
			}
			set
			{
				if ((this.@__9ism_cor != value))
				{
					this.On_9ism_corChanging(value);
					this.SendPropertyChanging();
					this.@__9ism_cor = value;
					this.SendPropertyChanged("_9ism_cor");
					this.On_9ism_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_arch_cor", DbType="NVarChar(50)")]
		public string type_arch_cor
		{
			get
			{
				return this._type_arch_cor;
			}
			set
			{
				if ((this._type_arch_cor != value))
				{
					this.Ontype_arch_corChanging(value);
					this.SendPropertyChanging();
					this._type_arch_cor = value;
					this.SendPropertyChanged("type_arch_cor");
					this.Ontype_arch_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classeIn_dossier", DbType="NVarChar(100)")]
		public string classeIn_dossier
		{
			get
			{
				return this._classeIn_dossier;
			}
			set
			{
				if ((this._classeIn_dossier != value))
				{
					this.OnclasseIn_dossierChanging(value);
					this.SendPropertyChanging();
					this._classeIn_dossier = value;
					this.SendPropertyChanged("classeIn_dossier");
					this.OnclasseIn_dossierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ref_doc_cor", DbType="Int")]
		public System.Nullable<int> ref_doc_cor
		{
			get
			{
				return this._ref_doc_cor;
			}
			set
			{
				if ((this._ref_doc_cor != value))
				{
					this.Onref_doc_corChanging(value);
					this.SendPropertyChanging();
					this._ref_doc_cor = value;
					this.SendPropertyChanged("ref_doc_cor");
					this.Onref_doc_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classIn_case_cor", DbType="Int")]
		public System.Nullable<int> classIn_case_cor
		{
			get
			{
				return this._classIn_case_cor;
			}
			set
			{
				if ((this._classIn_case_cor != value))
				{
					this.OnclassIn_case_corChanging(value);
					this.SendPropertyChanging();
					this._classIn_case_cor = value;
					this.SendPropertyChanged("classIn_case_cor");
					this.OnclassIn_case_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classIn_raf_cor", DbType="Int")]
		public System.Nullable<int> classIn_raf_cor
		{
			get
			{
				return this._classIn_raf_cor;
			}
			set
			{
				if ((this._classIn_raf_cor != value))
				{
					this.OnclassIn_raf_corChanging(value);
					this.SendPropertyChanging();
					this._classIn_raf_cor = value;
					this.SendPropertyChanged("classIn_raf_cor");
					this.OnclassIn_raf_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_locationPc_cor", DbType="NVarChar(MAX)")]
		public string locationPc_cor
		{
			get
			{
				return this._locationPc_cor;
			}
			set
			{
				if ((this._locationPc_cor != value))
				{
					this.OnlocationPc_corChanging(value);
					this.SendPropertyChanging();
					this._locationPc_cor = value;
					this.SendPropertyChanged("locationPc_cor");
					this.OnlocationPc_corChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gresa_cor", DbType="NVarChar(100)")]
		public string gresa_cor
		{
			get
			{
				return this._gresa_cor;
			}
			set
			{
				if ((this._gresa_cor != value))
				{
					this.Ongresa_corChanging(value);
					this.SendPropertyChanging();
					this._gresa_cor = value;
					this.SendPropertyChanged("gresa_cor");
					this.Ongresa_corChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.morasala_export")]
	public partial class morasala_export : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id_expo;
		
		private string _obj_expo;
		
		private string _product_expo;
		
		private string _distination_expo;
		
		private string _maslaha_expo;
		
		private string _maktab;
		
		private string _num_bord_expo;
		
		private System.Nullable<System.DateTime> _dt_expo;
		
		private string _distinee_expo;
		
		private string _path_expo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_expoChanging(string value);
    partial void OnId_expoChanged();
    partial void Onobj_expoChanging(string value);
    partial void Onobj_expoChanged();
    partial void Onproduct_expoChanging(string value);
    partial void Onproduct_expoChanged();
    partial void Ondistination_expoChanging(string value);
    partial void Ondistination_expoChanged();
    partial void Onmaslaha_expoChanging(string value);
    partial void Onmaslaha_expoChanged();
    partial void OnmaktabChanging(string value);
    partial void OnmaktabChanged();
    partial void Onnum_bord_expoChanging(string value);
    partial void Onnum_bord_expoChanged();
    partial void Ondt_expoChanging(System.Nullable<System.DateTime> value);
    partial void Ondt_expoChanged();
    partial void Ondistinee_expoChanging(string value);
    partial void Ondistinee_expoChanged();
    partial void Onpath_expoChanging(string value);
    partial void Onpath_expoChanged();
    #endregion
		
		public morasala_export()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_expo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_expo
		{
			get
			{
				return this._Id_expo;
			}
			set
			{
				if ((this._Id_expo != value))
				{
					this.OnId_expoChanging(value);
					this.SendPropertyChanging();
					this._Id_expo = value;
					this.SendPropertyChanged("Id_expo");
					this.OnId_expoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obj_expo", DbType="NVarChar(300)")]
		public string obj_expo
		{
			get
			{
				return this._obj_expo;
			}
			set
			{
				if ((this._obj_expo != value))
				{
					this.Onobj_expoChanging(value);
					this.SendPropertyChanging();
					this._obj_expo = value;
					this.SendPropertyChanged("obj_expo");
					this.Onobj_expoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_expo", DbType="NVarChar(50)")]
		public string product_expo
		{
			get
			{
				return this._product_expo;
			}
			set
			{
				if ((this._product_expo != value))
				{
					this.Onproduct_expoChanging(value);
					this.SendPropertyChanging();
					this._product_expo = value;
					this.SendPropertyChanged("product_expo");
					this.Onproduct_expoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distination_expo", DbType="NVarChar(50)")]
		public string distination_expo
		{
			get
			{
				return this._distination_expo;
			}
			set
			{
				if ((this._distination_expo != value))
				{
					this.Ondistination_expoChanging(value);
					this.SendPropertyChanging();
					this._distination_expo = value;
					this.SendPropertyChanged("distination_expo");
					this.Ondistination_expoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maslaha_expo", DbType="NVarChar(100)")]
		public string maslaha_expo
		{
			get
			{
				return this._maslaha_expo;
			}
			set
			{
				if ((this._maslaha_expo != value))
				{
					this.Onmaslaha_expoChanging(value);
					this.SendPropertyChanging();
					this._maslaha_expo = value;
					this.SendPropertyChanged("maslaha_expo");
					this.Onmaslaha_expoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maktab", DbType="NVarChar(100)")]
		public string maktab
		{
			get
			{
				return this._maktab;
			}
			set
			{
				if ((this._maktab != value))
				{
					this.OnmaktabChanging(value);
					this.SendPropertyChanging();
					this._maktab = value;
					this.SendPropertyChanged("maktab");
					this.OnmaktabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_bord_expo", DbType="NVarChar(50)")]
		public string num_bord_expo
		{
			get
			{
				return this._num_bord_expo;
			}
			set
			{
				if ((this._num_bord_expo != value))
				{
					this.Onnum_bord_expoChanging(value);
					this.SendPropertyChanging();
					this._num_bord_expo = value;
					this.SendPropertyChanged("num_bord_expo");
					this.Onnum_bord_expoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_expo", DbType="Date")]
		public System.Nullable<System.DateTime> dt_expo
		{
			get
			{
				return this._dt_expo;
			}
			set
			{
				if ((this._dt_expo != value))
				{
					this.Ondt_expoChanging(value);
					this.SendPropertyChanging();
					this._dt_expo = value;
					this.SendPropertyChanged("dt_expo");
					this.Ondt_expoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distinee_expo", DbType="NVarChar(50)")]
		public string distinee_expo
		{
			get
			{
				return this._distinee_expo;
			}
			set
			{
				if ((this._distinee_expo != value))
				{
					this.Ondistinee_expoChanging(value);
					this.SendPropertyChanging();
					this._distinee_expo = value;
					this.SendPropertyChanged("distinee_expo");
					this.Ondistinee_expoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_path_expo", DbType="NVarChar(300)")]
		public string path_expo
		{
			get
			{
				return this._path_expo;
			}
			set
			{
				if ((this._path_expo != value))
				{
					this.Onpath_expoChanging(value);
					this.SendPropertyChanging();
					this._path_expo = value;
					this.SendPropertyChanged("path_expo");
					this.Onpath_expoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.morasala_import")]
	public partial class morasala_import : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id_impo;
		
		private string _obj_impo;
		
		private string _product_impo;
		
		private string _distination_impo;
		
		private string _maslaha_impo;
		
		private string _maktab_impo;
		
		private string _num_bord__extern_empo;
		
		private System.Nullable<System.DateTime> _dt_impo;
		
		private string _distinee_impo;
		
		private string _path_impo;
		
		private string _num_bord__intern_empo;
		
		private System.Nullable<bool> _execute_impo;
		
		private string _delai_execut_impo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_impoChanging(string value);
    partial void OnId_impoChanged();
    partial void Onobj_impoChanging(string value);
    partial void Onobj_impoChanged();
    partial void Onproduct_impoChanging(string value);
    partial void Onproduct_impoChanged();
    partial void Ondistination_impoChanging(string value);
    partial void Ondistination_impoChanged();
    partial void Onmaslaha_impoChanging(string value);
    partial void Onmaslaha_impoChanged();
    partial void Onmaktab_impoChanging(string value);
    partial void Onmaktab_impoChanged();
    partial void Onnum_bord__extern_empoChanging(string value);
    partial void Onnum_bord__extern_empoChanged();
    partial void Ondt_impoChanging(System.Nullable<System.DateTime> value);
    partial void Ondt_impoChanged();
    partial void Ondistinee_impoChanging(string value);
    partial void Ondistinee_impoChanged();
    partial void Onpath_impoChanging(string value);
    partial void Onpath_impoChanged();
    partial void Onnum_bord__intern_empoChanging(string value);
    partial void Onnum_bord__intern_empoChanged();
    partial void Onexecute_impoChanging(System.Nullable<bool> value);
    partial void Onexecute_impoChanged();
    partial void Ondelai_execut_impoChanging(string value);
    partial void Ondelai_execut_impoChanged();
    #endregion
		
		public morasala_import()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_impo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_impo
		{
			get
			{
				return this._Id_impo;
			}
			set
			{
				if ((this._Id_impo != value))
				{
					this.OnId_impoChanging(value);
					this.SendPropertyChanging();
					this._Id_impo = value;
					this.SendPropertyChanged("Id_impo");
					this.OnId_impoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obj_impo", DbType="NVarChar(300)")]
		public string obj_impo
		{
			get
			{
				return this._obj_impo;
			}
			set
			{
				if ((this._obj_impo != value))
				{
					this.Onobj_impoChanging(value);
					this.SendPropertyChanging();
					this._obj_impo = value;
					this.SendPropertyChanged("obj_impo");
					this.Onobj_impoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_impo", DbType="NVarChar(50)")]
		public string product_impo
		{
			get
			{
				return this._product_impo;
			}
			set
			{
				if ((this._product_impo != value))
				{
					this.Onproduct_impoChanging(value);
					this.SendPropertyChanging();
					this._product_impo = value;
					this.SendPropertyChanged("product_impo");
					this.Onproduct_impoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distination_impo", DbType="NVarChar(50)")]
		public string distination_impo
		{
			get
			{
				return this._distination_impo;
			}
			set
			{
				if ((this._distination_impo != value))
				{
					this.Ondistination_impoChanging(value);
					this.SendPropertyChanging();
					this._distination_impo = value;
					this.SendPropertyChanged("distination_impo");
					this.Ondistination_impoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maslaha_impo", DbType="NVarChar(100)")]
		public string maslaha_impo
		{
			get
			{
				return this._maslaha_impo;
			}
			set
			{
				if ((this._maslaha_impo != value))
				{
					this.Onmaslaha_impoChanging(value);
					this.SendPropertyChanging();
					this._maslaha_impo = value;
					this.SendPropertyChanged("maslaha_impo");
					this.Onmaslaha_impoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maktab_impo", DbType="NVarChar(100)")]
		public string maktab_impo
		{
			get
			{
				return this._maktab_impo;
			}
			set
			{
				if ((this._maktab_impo != value))
				{
					this.Onmaktab_impoChanging(value);
					this.SendPropertyChanging();
					this._maktab_impo = value;
					this.SendPropertyChanged("maktab_impo");
					this.Onmaktab_impoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_bord__extern_empo", DbType="NVarChar(50)")]
		public string num_bord__extern_empo
		{
			get
			{
				return this._num_bord__extern_empo;
			}
			set
			{
				if ((this._num_bord__extern_empo != value))
				{
					this.Onnum_bord__extern_empoChanging(value);
					this.SendPropertyChanging();
					this._num_bord__extern_empo = value;
					this.SendPropertyChanged("num_bord__extern_empo");
					this.Onnum_bord__extern_empoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_impo", DbType="Date")]
		public System.Nullable<System.DateTime> dt_impo
		{
			get
			{
				return this._dt_impo;
			}
			set
			{
				if ((this._dt_impo != value))
				{
					this.Ondt_impoChanging(value);
					this.SendPropertyChanging();
					this._dt_impo = value;
					this.SendPropertyChanged("dt_impo");
					this.Ondt_impoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distinee_impo", DbType="NVarChar(50)")]
		public string distinee_impo
		{
			get
			{
				return this._distinee_impo;
			}
			set
			{
				if ((this._distinee_impo != value))
				{
					this.Ondistinee_impoChanging(value);
					this.SendPropertyChanging();
					this._distinee_impo = value;
					this.SendPropertyChanged("distinee_impo");
					this.Ondistinee_impoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_path_impo", DbType="NVarChar(300)")]
		public string path_impo
		{
			get
			{
				return this._path_impo;
			}
			set
			{
				if ((this._path_impo != value))
				{
					this.Onpath_impoChanging(value);
					this.SendPropertyChanging();
					this._path_impo = value;
					this.SendPropertyChanged("path_impo");
					this.Onpath_impoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_bord__intern_empo", DbType="NChar(10)")]
		public string num_bord__intern_empo
		{
			get
			{
				return this._num_bord__intern_empo;
			}
			set
			{
				if ((this._num_bord__intern_empo != value))
				{
					this.Onnum_bord__intern_empoChanging(value);
					this.SendPropertyChanging();
					this._num_bord__intern_empo = value;
					this.SendPropertyChanged("num_bord__intern_empo");
					this.Onnum_bord__intern_empoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_execute_impo", DbType="Bit")]
		public System.Nullable<bool> execute_impo
		{
			get
			{
				return this._execute_impo;
			}
			set
			{
				if ((this._execute_impo != value))
				{
					this.Onexecute_impoChanging(value);
					this.SendPropertyChanging();
					this._execute_impo = value;
					this.SendPropertyChanged("execute_impo");
					this.Onexecute_impoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delai_execut_impo", DbType="NChar(10)")]
		public string delai_execut_impo
		{
			get
			{
				return this._delai_execut_impo;
			}
			set
			{
				if ((this._delai_execut_impo != value))
				{
					this.Ondelai_execut_impoChanging(value);
					this.SendPropertyChanging();
					this._delai_execut_impo = value;
					this.SendPropertyChanged("delai_execut_impo");
					this.Ondelai_execut_impoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pathclasse")]
	public partial class pathclasse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cl_pth_id;
		
		private string _greasa_path;
		
		private string _classe_path;
		
		private string _niveau_path;
		
		private string _cycle_path;
		
		private string _typeEnseign_path;
		
		private string _annescol_path;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncl_pth_idChanging(string value);
    partial void Oncl_pth_idChanged();
    partial void Ongreasa_pathChanging(string value);
    partial void Ongreasa_pathChanged();
    partial void Onclasse_pathChanging(string value);
    partial void Onclasse_pathChanged();
    partial void Onniveau_pathChanging(string value);
    partial void Onniveau_pathChanged();
    partial void Oncycle_pathChanging(string value);
    partial void Oncycle_pathChanged();
    partial void OntypeEnseign_pathChanging(string value);
    partial void OntypeEnseign_pathChanged();
    partial void Onannescol_pathChanging(string value);
    partial void Onannescol_pathChanged();
    #endregion
		
		public pathclasse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_pth_id", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cl_pth_id
		{
			get
			{
				return this._cl_pth_id;
			}
			set
			{
				if ((this._cl_pth_id != value))
				{
					this.Oncl_pth_idChanging(value);
					this.SendPropertyChanging();
					this._cl_pth_id = value;
					this.SendPropertyChanged("cl_pth_id");
					this.Oncl_pth_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_greasa_path", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string greasa_path
		{
			get
			{
				return this._greasa_path;
			}
			set
			{
				if ((this._greasa_path != value))
				{
					this.Ongreasa_pathChanging(value);
					this.SendPropertyChanging();
					this._greasa_path = value;
					this.SendPropertyChanged("greasa_path");
					this.Ongreasa_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classe_path", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string classe_path
		{
			get
			{
				return this._classe_path;
			}
			set
			{
				if ((this._classe_path != value))
				{
					this.Onclasse_pathChanging(value);
					this.SendPropertyChanging();
					this._classe_path = value;
					this.SendPropertyChanged("classe_path");
					this.Onclasse_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niveau_path", DbType="NVarChar(100)")]
		public string niveau_path
		{
			get
			{
				return this._niveau_path;
			}
			set
			{
				if ((this._niveau_path != value))
				{
					this.Onniveau_pathChanging(value);
					this.SendPropertyChanging();
					this._niveau_path = value;
					this.SendPropertyChanged("niveau_path");
					this.Onniveau_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cycle_path", DbType="NVarChar(100)")]
		public string cycle_path
		{
			get
			{
				return this._cycle_path;
			}
			set
			{
				if ((this._cycle_path != value))
				{
					this.Oncycle_pathChanging(value);
					this.SendPropertyChanging();
					this._cycle_path = value;
					this.SendPropertyChanged("cycle_path");
					this.Oncycle_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeEnseign_path", DbType="NVarChar(100)")]
		public string typeEnseign_path
		{
			get
			{
				return this._typeEnseign_path;
			}
			set
			{
				if ((this._typeEnseign_path != value))
				{
					this.OntypeEnseign_pathChanging(value);
					this.SendPropertyChanging();
					this._typeEnseign_path = value;
					this.SendPropertyChanged("typeEnseign_path");
					this.OntypeEnseign_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_annescol_path", DbType="NVarChar(50)")]
		public string annescol_path
		{
			get
			{
				return this._annescol_path;
			}
			set
			{
				if ((this._annescol_path != value))
				{
					this.Onannescol_pathChanging(value);
					this.SendPropertyChanging();
					this._annescol_path = value;
					this.SendPropertyChanged("annescol_path");
					this.Onannescol_pathChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.raf")]
	public partial class raf : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_raf;
		
		private string _raf_raf;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_rafChanging(int value);
    partial void OnId_rafChanged();
    partial void Onraf_rafChanging(string value);
    partial void Onraf_rafChanged();
    #endregion
		
		public raf()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_raf", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_raf
		{
			get
			{
				return this._Id_raf;
			}
			set
			{
				if ((this._Id_raf != value))
				{
					this.OnId_rafChanging(value);
					this.SendPropertyChanging();
					this._Id_raf = value;
					this.SendPropertyChanged("Id_raf");
					this.OnId_rafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raf_raf", DbType="NVarChar(100)")]
		public string raf_raf
		{
			get
			{
				return this._raf_raf;
			}
			set
			{
				if ((this._raf_raf != value))
				{
					this.Onraf_rafChanging(value);
					this.SendPropertyChanging();
					this._raf_raf = value;
					this.SendPropertyChanged("raf_raf");
					this.Onraf_rafChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.raff")]
	public partial class raff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_raf;
		
		private string _nom_raf;
		
		private string _cod_raf;
		
		private string _khiz_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_rafChanging(string value);
    partial void Onid_rafChanged();
    partial void Onnom_rafChanging(string value);
    partial void Onnom_rafChanged();
    partial void Oncod_rafChanging(string value);
    partial void Oncod_rafChanged();
    partial void Onkhiz_idChanging(string value);
    partial void Onkhiz_idChanged();
    #endregion
		
		public raff()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_raf", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_raf
		{
			get
			{
				return this._id_raf;
			}
			set
			{
				if ((this._id_raf != value))
				{
					this.Onid_rafChanging(value);
					this.SendPropertyChanging();
					this._id_raf = value;
					this.SendPropertyChanged("id_raf");
					this.Onid_rafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_raf", DbType="NVarChar(100)")]
		public string nom_raf
		{
			get
			{
				return this._nom_raf;
			}
			set
			{
				if ((this._nom_raf != value))
				{
					this.Onnom_rafChanging(value);
					this.SendPropertyChanging();
					this._nom_raf = value;
					this.SendPropertyChanged("nom_raf");
					this.Onnom_rafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_raf", DbType="NVarChar(50)")]
		public string cod_raf
		{
			get
			{
				return this._cod_raf;
			}
			set
			{
				if ((this._cod_raf != value))
				{
					this.Oncod_rafChanging(value);
					this.SendPropertyChanging();
					this._cod_raf = value;
					this.SendPropertyChanged("cod_raf");
					this.Oncod_rafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khiz_id", DbType="NVarChar(50)")]
		public string khiz_id
		{
			get
			{
				return this._khiz_id;
			}
			set
			{
				if ((this._khiz_id != value))
				{
					this.Onkhiz_idChanging(value);
					this.SendPropertyChanging();
					this._khiz_id = value;
					this.SendPropertyChanged("khiz_id");
					this.Onkhiz_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.saf_khizana")]
	public partial class saf_khizana : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id_saf;
		
		private string _nom_saf;
		
		private string _code_saf;
		
		private string _dipot_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_safChanging(string value);
    partial void OnId_safChanged();
    partial void Onnom_safChanging(string value);
    partial void Onnom_safChanged();
    partial void Oncode_safChanging(string value);
    partial void Oncode_safChanged();
    partial void Ondipot_idChanging(string value);
    partial void Ondipot_idChanged();
    #endregion
		
		public saf_khizana()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_saf", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_saf
		{
			get
			{
				return this._Id_saf;
			}
			set
			{
				if ((this._Id_saf != value))
				{
					this.OnId_safChanging(value);
					this.SendPropertyChanging();
					this._Id_saf = value;
					this.SendPropertyChanged("Id_saf");
					this.OnId_safChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_saf", DbType="NVarChar(100)")]
		public string nom_saf
		{
			get
			{
				return this._nom_saf;
			}
			set
			{
				if ((this._nom_saf != value))
				{
					this.Onnom_safChanging(value);
					this.SendPropertyChanging();
					this._nom_saf = value;
					this.SendPropertyChanged("nom_saf");
					this.Onnom_safChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_saf", DbType="NVarChar(50)")]
		public string code_saf
		{
			get
			{
				return this._code_saf;
			}
			set
			{
				if ((this._code_saf != value))
				{
					this.Oncode_safChanging(value);
					this.SendPropertyChanging();
					this._code_saf = value;
					this.SendPropertyChanged("code_saf");
					this.Oncode_safChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dipot_id", DbType="NVarChar(50)")]
		public string dipot_id
		{
			get
			{
				return this._dipot_id;
			}
			set
			{
				if ((this._dipot_id != value))
				{
					this.Ondipot_idChanging(value);
					this.SendPropertyChanging();
					this._dipot_id = value;
					this.SendPropertyChanged("dipot_id");
					this.Ondipot_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
