#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schooly
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="exam")]
	public partial class examenDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertlevel_ex(level_ex instance);
    partial void Updatelevel_ex(level_ex instance);
    partial void Deletelevel_ex(level_ex instance);
    partial void Insertstudents_ex(students_ex instance);
    partial void Updatestudents_ex(students_ex instance);
    partial void Deletestudents_ex(students_ex instance);
    partial void Insertsubject_ex(subject_ex instance);
    partial void Updatesubject_ex(subject_ex instance);
    partial void Deletesubject_ex(subject_ex instance);
    #endregion
		
		public examenDataContext() : 
				base(global::Schooly.Properties.Settings.Default.examConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public examenDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public examenDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public examenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public examenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<level_ex> level_exes
		{
			get
			{
				return this.GetTable<level_ex>();
			}
		}
		
		public System.Data.Linq.Table<students_ex> students_exes
		{
			get
			{
				return this.GetTable<students_ex>();
			}
		}
		
		public System.Data.Linq.Table<subject_ex> subject_exes
		{
			get
			{
				return this.GetTable<subject_ex>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.level_ex")]
	public partial class level_ex : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _level_id;
		
		private string _level_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlevel_idChanging(int value);
    partial void Onlevel_idChanged();
    partial void Onlevel_nameChanging(string value);
    partial void Onlevel_nameChanged();
    #endregion
		
		public level_ex()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_level_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int level_id
		{
			get
			{
				return this._level_id;
			}
			set
			{
				if ((this._level_id != value))
				{
					this.Onlevel_idChanging(value);
					this.SendPropertyChanging();
					this._level_id = value;
					this.SendPropertyChanged("level_id");
					this.Onlevel_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_level_name", DbType="NVarChar(50)")]
		public string level_name
		{
			get
			{
				return this._level_name;
			}
			set
			{
				if ((this._level_name != value))
				{
					this.Onlevel_nameChanging(value);
					this.SendPropertyChanging();
					this._level_name = value;
					this.SendPropertyChanged("level_name");
					this.Onlevel_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.students_ex")]
	public partial class students_ex : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cmassar_ex;
		
		private string _fname_ex;
		
		private string _lname_ex;
		
		private System.Nullable<System.DateTime> _birth_ex;
		
		private System.Nullable<int> _level_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncmassar_exChanging(string value);
    partial void Oncmassar_exChanged();
    partial void Onfname_exChanging(string value);
    partial void Onfname_exChanged();
    partial void Onlname_exChanging(string value);
    partial void Onlname_exChanged();
    partial void Onbirth_exChanging(System.Nullable<System.DateTime> value);
    partial void Onbirth_exChanged();
    partial void Onlevel_IDChanging(System.Nullable<int> value);
    partial void Onlevel_IDChanged();
    #endregion
		
		public students_ex()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmassar_ex", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cmassar_ex
		{
			get
			{
				return this._cmassar_ex;
			}
			set
			{
				if ((this._cmassar_ex != value))
				{
					this.Oncmassar_exChanging(value);
					this.SendPropertyChanging();
					this._cmassar_ex = value;
					this.SendPropertyChanged("cmassar_ex");
					this.Oncmassar_exChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname_ex", DbType="NVarChar(50)")]
		public string fname_ex
		{
			get
			{
				return this._fname_ex;
			}
			set
			{
				if ((this._fname_ex != value))
				{
					this.Onfname_exChanging(value);
					this.SendPropertyChanging();
					this._fname_ex = value;
					this.SendPropertyChanged("fname_ex");
					this.Onfname_exChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname_ex", DbType="NVarChar(50)")]
		public string lname_ex
		{
			get
			{
				return this._lname_ex;
			}
			set
			{
				if ((this._lname_ex != value))
				{
					this.Onlname_exChanging(value);
					this.SendPropertyChanging();
					this._lname_ex = value;
					this.SendPropertyChanged("lname_ex");
					this.Onlname_exChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth_ex", DbType="Date")]
		public System.Nullable<System.DateTime> birth_ex
		{
			get
			{
				return this._birth_ex;
			}
			set
			{
				if ((this._birth_ex != value))
				{
					this.Onbirth_exChanging(value);
					this.SendPropertyChanging();
					this._birth_ex = value;
					this.SendPropertyChanged("birth_ex");
					this.Onbirth_exChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_level_ID", DbType="Int")]
		public System.Nullable<int> level_ID
		{
			get
			{
				return this._level_ID;
			}
			set
			{
				if ((this._level_ID != value))
				{
					this.Onlevel_IDChanging(value);
					this.SendPropertyChanging();
					this._level_ID = value;
					this.SendPropertyChanged("level_ID");
					this.Onlevel_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.subject_ex")]
	public partial class subject_ex : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _subject_id;
		
		private string _subject_name_ex;
		
		private string _day_ex;
		
		private System.Nullable<int> _start_hour_ex;
		
		private System.Nullable<int> _start_minute_ex;
		
		private System.Nullable<int> _end_hour_ex;
		
		private System.Nullable<int> _end_minute_ex;
		
		private System.Nullable<int> _level_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsubject_idChanging(int value);
    partial void Onsubject_idChanged();
    partial void Onsubject_name_exChanging(string value);
    partial void Onsubject_name_exChanged();
    partial void Onday_exChanging(string value);
    partial void Onday_exChanged();
    partial void Onstart_hour_exChanging(System.Nullable<int> value);
    partial void Onstart_hour_exChanged();
    partial void Onstart_minute_exChanging(System.Nullable<int> value);
    partial void Onstart_minute_exChanged();
    partial void Onend_hour_exChanging(System.Nullable<int> value);
    partial void Onend_hour_exChanged();
    partial void Onend_minute_exChanging(System.Nullable<int> value);
    partial void Onend_minute_exChanged();
    partial void Onlevel_idChanging(System.Nullable<int> value);
    partial void Onlevel_idChanged();
    #endregion
		
		public subject_ex()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int subject_id
		{
			get
			{
				return this._subject_id;
			}
			set
			{
				if ((this._subject_id != value))
				{
					this.Onsubject_idChanging(value);
					this.SendPropertyChanging();
					this._subject_id = value;
					this.SendPropertyChanged("subject_id");
					this.Onsubject_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_name_ex", DbType="NVarChar(100)")]
		public string subject_name_ex
		{
			get
			{
				return this._subject_name_ex;
			}
			set
			{
				if ((this._subject_name_ex != value))
				{
					this.Onsubject_name_exChanging(value);
					this.SendPropertyChanging();
					this._subject_name_ex = value;
					this.SendPropertyChanged("subject_name_ex");
					this.Onsubject_name_exChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day_ex", DbType="NVarChar(20)")]
		public string day_ex
		{
			get
			{
				return this._day_ex;
			}
			set
			{
				if ((this._day_ex != value))
				{
					this.Onday_exChanging(value);
					this.SendPropertyChanging();
					this._day_ex = value;
					this.SendPropertyChanged("day_ex");
					this.Onday_exChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_hour_ex", DbType="Int")]
		public System.Nullable<int> start_hour_ex
		{
			get
			{
				return this._start_hour_ex;
			}
			set
			{
				if ((this._start_hour_ex != value))
				{
					this.Onstart_hour_exChanging(value);
					this.SendPropertyChanging();
					this._start_hour_ex = value;
					this.SendPropertyChanged("start_hour_ex");
					this.Onstart_hour_exChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_minute_ex", DbType="Int")]
		public System.Nullable<int> start_minute_ex
		{
			get
			{
				return this._start_minute_ex;
			}
			set
			{
				if ((this._start_minute_ex != value))
				{
					this.Onstart_minute_exChanging(value);
					this.SendPropertyChanging();
					this._start_minute_ex = value;
					this.SendPropertyChanged("start_minute_ex");
					this.Onstart_minute_exChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_hour_ex", DbType="Int")]
		public System.Nullable<int> end_hour_ex
		{
			get
			{
				return this._end_hour_ex;
			}
			set
			{
				if ((this._end_hour_ex != value))
				{
					this.Onend_hour_exChanging(value);
					this.SendPropertyChanging();
					this._end_hour_ex = value;
					this.SendPropertyChanged("end_hour_ex");
					this.Onend_hour_exChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_minute_ex", DbType="Int")]
		public System.Nullable<int> end_minute_ex
		{
			get
			{
				return this._end_minute_ex;
			}
			set
			{
				if ((this._end_minute_ex != value))
				{
					this.Onend_minute_exChanging(value);
					this.SendPropertyChanging();
					this._end_minute_ex = value;
					this.SendPropertyChanged("end_minute_ex");
					this.Onend_minute_exChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_level_id", DbType="Int")]
		public System.Nullable<int> level_id
		{
			get
			{
				return this._level_id;
			}
			set
			{
				if ((this._level_id != value))
				{
					this.Onlevel_idChanging(value);
					this.SendPropertyChanging();
					this._level_id = value;
					this.SendPropertyChanged("level_id");
					this.Onlevel_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
