#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schooly
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="fet")]
	public partial class fetDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertelevess(elevess instance);
    partial void Updateelevess(elevess instance);
    partial void Deleteelevess(elevess instance);
    partial void Insertsubject(subject instance);
    partial void Updatesubject(subject instance);
    partial void Deletesubject(subject instance);
    partial void Inserttecher(techer instance);
    partial void Updatetecher(techer instance);
    partial void Deletetecher(techer instance);
    partial void InserttimeTable(timeTable instance);
    partial void UpdatetimeTable(timeTable instance);
    partial void DeletetimeTable(timeTable instance);
    #endregion
		
		public fetDataContext() : 
				base(global::Schooly.Properties.Settings.Default.fetConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public fetDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public fetDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public fetDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public fetDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<elevess> elevesses
		{
			get
			{
				return this.GetTable<elevess>();
			}
		}
		
		public System.Data.Linq.Table<subject> subjects
		{
			get
			{
				return this.GetTable<subject>();
			}
		}
		
		public System.Data.Linq.Table<techer> techers
		{
			get
			{
				return this.GetTable<techer>();
			}
		}
		
		public System.Data.Linq.Table<timeTable> timeTables
		{
			get
			{
				return this.GetTable<timeTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.elevess")]
	public partial class elevess : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_st;
		
		private string _Year;
		
		private System.Nullable<int> _NuOfStPerYear;
		
		private string _groups;
		
		private System.Nullable<int> _NuOfStPerGroup;
		
		private string _Subgroup;
		
		private System.Nullable<int> _NuOfStPerSubgroup;
		
		private string _gresa_el_fet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_stChanging(int value);
    partial void OnId_stChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    partial void OnNuOfStPerYearChanging(System.Nullable<int> value);
    partial void OnNuOfStPerYearChanged();
    partial void OngroupsChanging(string value);
    partial void OngroupsChanged();
    partial void OnNuOfStPerGroupChanging(System.Nullable<int> value);
    partial void OnNuOfStPerGroupChanged();
    partial void OnSubgroupChanging(string value);
    partial void OnSubgroupChanged();
    partial void OnNuOfStPerSubgroupChanging(System.Nullable<int> value);
    partial void OnNuOfStPerSubgroupChanged();
    partial void Ongresa_el_fetChanging(string value);
    partial void Ongresa_el_fetChanged();
    #endregion
		
		public elevess()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_st", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_st
		{
			get
			{
				return this._Id_st;
			}
			set
			{
				if ((this._Id_st != value))
				{
					this.OnId_stChanging(value);
					this.SendPropertyChanging();
					this._Id_st = value;
					this.SendPropertyChanged("Id_st");
					this.OnId_stChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(50)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NuOfStPerYear", DbType="Int")]
		public System.Nullable<int> NuOfStPerYear
		{
			get
			{
				return this._NuOfStPerYear;
			}
			set
			{
				if ((this._NuOfStPerYear != value))
				{
					this.OnNuOfStPerYearChanging(value);
					this.SendPropertyChanging();
					this._NuOfStPerYear = value;
					this.SendPropertyChanged("NuOfStPerYear");
					this.OnNuOfStPerYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groups", DbType="NVarChar(50)")]
		public string groups
		{
			get
			{
				return this._groups;
			}
			set
			{
				if ((this._groups != value))
				{
					this.OngroupsChanging(value);
					this.SendPropertyChanging();
					this._groups = value;
					this.SendPropertyChanged("groups");
					this.OngroupsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NuOfStPerGroup", DbType="Int")]
		public System.Nullable<int> NuOfStPerGroup
		{
			get
			{
				return this._NuOfStPerGroup;
			}
			set
			{
				if ((this._NuOfStPerGroup != value))
				{
					this.OnNuOfStPerGroupChanging(value);
					this.SendPropertyChanging();
					this._NuOfStPerGroup = value;
					this.SendPropertyChanged("NuOfStPerGroup");
					this.OnNuOfStPerGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subgroup", DbType="NVarChar(50)")]
		public string Subgroup
		{
			get
			{
				return this._Subgroup;
			}
			set
			{
				if ((this._Subgroup != value))
				{
					this.OnSubgroupChanging(value);
					this.SendPropertyChanging();
					this._Subgroup = value;
					this.SendPropertyChanged("Subgroup");
					this.OnSubgroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NuOfStPerSubgroup", DbType="Int")]
		public System.Nullable<int> NuOfStPerSubgroup
		{
			get
			{
				return this._NuOfStPerSubgroup;
			}
			set
			{
				if ((this._NuOfStPerSubgroup != value))
				{
					this.OnNuOfStPerSubgroupChanging(value);
					this.SendPropertyChanging();
					this._NuOfStPerSubgroup = value;
					this.SendPropertyChanged("NuOfStPerSubgroup");
					this.OnNuOfStPerSubgroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gresa_el_fet", DbType="NVarChar(50)")]
		public string gresa_el_fet
		{
			get
			{
				return this._gresa_el_fet;
			}
			set
			{
				if ((this._gresa_el_fet != value))
				{
					this.Ongresa_el_fetChanging(value);
					this.SendPropertyChanging();
					this._gresa_el_fet = value;
					this.SendPropertyChanged("gresa_el_fet");
					this.Ongresa_el_fetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.subjects")]
	public partial class subject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_sub;
		
		private string _Subject1;
		
		private string _gresa_sub_fet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_subChanging(int value);
    partial void OnId_subChanged();
    partial void OnSubject1Changing(string value);
    partial void OnSubject1Changed();
    partial void Ongresa_sub_fetChanging(string value);
    partial void Ongresa_sub_fetChanged();
    #endregion
		
		public subject()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_sub", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_sub
		{
			get
			{
				return this._Id_sub;
			}
			set
			{
				if ((this._Id_sub != value))
				{
					this.OnId_subChanging(value);
					this.SendPropertyChanging();
					this._Id_sub = value;
					this.SendPropertyChanged("Id_sub");
					this.OnId_subChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Subject", Storage="_Subject1", DbType="NVarChar(150)")]
		public string Subject1
		{
			get
			{
				return this._Subject1;
			}
			set
			{
				if ((this._Subject1 != value))
				{
					this.OnSubject1Changing(value);
					this.SendPropertyChanging();
					this._Subject1 = value;
					this.SendPropertyChanged("Subject1");
					this.OnSubject1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gresa_sub_fet", DbType="NVarChar(50)")]
		public string gresa_sub_fet
		{
			get
			{
				return this._gresa_sub_fet;
			}
			set
			{
				if ((this._gresa_sub_fet != value))
				{
					this.Ongresa_sub_fetChanging(value);
					this.SendPropertyChanging();
					this._gresa_sub_fet = value;
					this.SendPropertyChanged("gresa_sub_fet");
					this.Ongresa_sub_fetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.techers")]
	public partial class techer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_tech;
		
		private string _Teacher;
		
		private System.Nullable<int> _ppr;
		
		private string _gresa_tech_fet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_techChanging(int value);
    partial void OnId_techChanged();
    partial void OnTeacherChanging(string value);
    partial void OnTeacherChanged();
    partial void OnpprChanging(System.Nullable<int> value);
    partial void OnpprChanged();
    partial void Ongresa_tech_fetChanging(string value);
    partial void Ongresa_tech_fetChanged();
    #endregion
		
		public techer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_tech", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_tech
		{
			get
			{
				return this._Id_tech;
			}
			set
			{
				if ((this._Id_tech != value))
				{
					this.OnId_techChanging(value);
					this.SendPropertyChanging();
					this._Id_tech = value;
					this.SendPropertyChanged("Id_tech");
					this.OnId_techChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teacher", DbType="NVarChar(100)")]
		public string Teacher
		{
			get
			{
				return this._Teacher;
			}
			set
			{
				if ((this._Teacher != value))
				{
					this.OnTeacherChanging(value);
					this.SendPropertyChanging();
					this._Teacher = value;
					this.SendPropertyChanged("Teacher");
					this.OnTeacherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ppr", DbType="Int")]
		public System.Nullable<int> ppr
		{
			get
			{
				return this._ppr;
			}
			set
			{
				if ((this._ppr != value))
				{
					this.OnpprChanging(value);
					this.SendPropertyChanging();
					this._ppr = value;
					this.SendPropertyChanged("ppr");
					this.OnpprChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gresa_tech_fet", DbType="NVarChar(50)")]
		public string gresa_tech_fet
		{
			get
			{
				return this._gresa_tech_fet;
			}
			set
			{
				if ((this._gresa_tech_fet != value))
				{
					this.Ongresa_tech_fetChanging(value);
					this.SendPropertyChanging();
					this._gresa_tech_fet = value;
					this.SendPropertyChanged("gresa_tech_fet");
					this.Ongresa_tech_fetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.timeTable")]
	public partial class timeTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tt;
		
		private string _ActivityId;
		
		private System.Nullable<int> _Day;
		
		private System.Nullable<int> _Hour;
		
		private string _StudentsSets;
		
		private string _Subject;
		
		private string _Teachers;
		
		private string _ActivityTags;
		
		private string _Room;
		
		private string _Comments;
		
		private string _gresa_tt_fet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ttChanging(int value);
    partial void Onid_ttChanged();
    partial void OnActivityIdChanging(string value);
    partial void OnActivityIdChanged();
    partial void OnDayChanging(System.Nullable<int> value);
    partial void OnDayChanged();
    partial void OnHourChanging(System.Nullable<int> value);
    partial void OnHourChanged();
    partial void OnStudentsSetsChanging(string value);
    partial void OnStudentsSetsChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnTeachersChanging(string value);
    partial void OnTeachersChanged();
    partial void OnActivityTagsChanging(string value);
    partial void OnActivityTagsChanged();
    partial void OnRoomChanging(string value);
    partial void OnRoomChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void Ongresa_tt_fetChanging(string value);
    partial void Ongresa_tt_fetChanged();
    #endregion
		
		public timeTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tt", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tt
		{
			get
			{
				return this._id_tt;
			}
			set
			{
				if ((this._id_tt != value))
				{
					this.Onid_ttChanging(value);
					this.SendPropertyChanging();
					this._id_tt = value;
					this.SendPropertyChanged("id_tt");
					this.Onid_ttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityId", DbType="NVarChar(50)")]
		public string ActivityId
		{
			get
			{
				return this._ActivityId;
			}
			set
			{
				if ((this._ActivityId != value))
				{
					this.OnActivityIdChanging(value);
					this.SendPropertyChanging();
					this._ActivityId = value;
					this.SendPropertyChanged("ActivityId");
					this.OnActivityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Int")]
		public System.Nullable<int> Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this.OnDayChanging(value);
					this.SendPropertyChanging();
					this._Day = value;
					this.SendPropertyChanged("Day");
					this.OnDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hour", DbType="Int")]
		public System.Nullable<int> Hour
		{
			get
			{
				return this._Hour;
			}
			set
			{
				if ((this._Hour != value))
				{
					this.OnHourChanging(value);
					this.SendPropertyChanging();
					this._Hour = value;
					this.SendPropertyChanged("Hour");
					this.OnHourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentsSets", DbType="NVarChar(50)")]
		public string StudentsSets
		{
			get
			{
				return this._StudentsSets;
			}
			set
			{
				if ((this._StudentsSets != value))
				{
					this.OnStudentsSetsChanging(value);
					this.SendPropertyChanging();
					this._StudentsSets = value;
					this.SendPropertyChanged("StudentsSets");
					this.OnStudentsSetsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(50)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teachers", DbType="NVarChar(100)")]
		public string Teachers
		{
			get
			{
				return this._Teachers;
			}
			set
			{
				if ((this._Teachers != value))
				{
					this.OnTeachersChanging(value);
					this.SendPropertyChanging();
					this._Teachers = value;
					this.SendPropertyChanged("Teachers");
					this.OnTeachersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityTags", DbType="NVarChar(100)")]
		public string ActivityTags
		{
			get
			{
				return this._ActivityTags;
			}
			set
			{
				if ((this._ActivityTags != value))
				{
					this.OnActivityTagsChanging(value);
					this.SendPropertyChanging();
					this._ActivityTags = value;
					this.SendPropertyChanged("ActivityTags");
					this.OnActivityTagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room", DbType="NVarChar(50)")]
		public string Room
		{
			get
			{
				return this._Room;
			}
			set
			{
				if ((this._Room != value))
				{
					this.OnRoomChanging(value);
					this.SendPropertyChanging();
					this._Room = value;
					this.SendPropertyChanged("Room");
					this.OnRoomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NVarChar(200)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gresa_tt_fet", DbType="NVarChar(50)")]
		public string gresa_tt_fet
		{
			get
			{
				return this._gresa_tt_fet;
			}
			set
			{
				if ((this._gresa_tt_fet != value))
				{
					this.Ongresa_tt_fetChanging(value);
					this.SendPropertyChanging();
					this._gresa_tt_fet = value;
					this.SendPropertyChanged("gresa_tt_fet");
					this.Ongresa_tt_fetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
