#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schooly
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Students")]
	public partial class StudentsListDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStudentListPrimaire(StudentListPrimaire instance);
    partial void UpdateStudentListPrimaire(StudentListPrimaire instance);
    partial void DeleteStudentListPrimaire(StudentListPrimaire instance);
    partial void InsertStudentListUpdate(StudentListUpdate instance);
    partial void UpdateStudentListUpdate(StudentListUpdate instance);
    partial void DeleteStudentListUpdate(StudentListUpdate instance);
    partial void InsertTransaction(Transaction instance);
    partial void UpdateTransaction(Transaction instance);
    partial void DeleteTransaction(Transaction instance);
    #endregion
		
		public StudentsListDataContext() : 
				base(global::Schooly.Properties.Settings.Default.StudentsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StudentsListDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentsListDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentsListDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentsListDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StudentListPrimaire> StudentListPrimaires
		{
			get
			{
				return this.GetTable<StudentListPrimaire>();
			}
		}
		
		public System.Data.Linq.Table<StudentListUpdate> StudentListUpdates
		{
			get
			{
				return this.GetTable<StudentListUpdate>();
			}
		}
		
		public System.Data.Linq.Table<Transaction> Transactions
		{
			get
			{
				return this.GetTable<Transaction>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentListPrimaire")]
	public partial class StudentListPrimaire : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cMassar_Pr;
		
		private string _firstName_Pr;
		
		private string _lastName_Pr;
		
		private string _genre_Pr;
		
		private System.Nullable<System.DateTime> _dateNaiss_Pr;
		
		private string _lieuNaiss_Pr;
		
		private System.Nullable<int> _nOreder_Pr;
		
		private string _classe_Pr;
		
		private string _niveau_Pr;
		
		private string _gresa_Pr;
		
		private string _annescol_Pr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncMassar_PrChanging(string value);
    partial void OncMassar_PrChanged();
    partial void OnfirstName_PrChanging(string value);
    partial void OnfirstName_PrChanged();
    partial void OnlastName_PrChanging(string value);
    partial void OnlastName_PrChanged();
    partial void Ongenre_PrChanging(string value);
    partial void Ongenre_PrChanged();
    partial void OndateNaiss_PrChanging(System.Nullable<System.DateTime> value);
    partial void OndateNaiss_PrChanged();
    partial void OnlieuNaiss_PrChanging(string value);
    partial void OnlieuNaiss_PrChanged();
    partial void OnnOreder_PrChanging(System.Nullable<int> value);
    partial void OnnOreder_PrChanged();
    partial void Onclasse_PrChanging(string value);
    partial void Onclasse_PrChanged();
    partial void Onniveau_PrChanging(string value);
    partial void Onniveau_PrChanged();
    partial void Ongresa_PrChanging(string value);
    partial void Ongresa_PrChanged();
    partial void Onannescol_PrChanging(string value);
    partial void Onannescol_PrChanged();
    #endregion
		
		public StudentListPrimaire()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cMassar_Pr", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cMassar_Pr
		{
			get
			{
				return this._cMassar_Pr;
			}
			set
			{
				if ((this._cMassar_Pr != value))
				{
					this.OncMassar_PrChanging(value);
					this.SendPropertyChanging();
					this._cMassar_Pr = value;
					this.SendPropertyChanged("cMassar_Pr");
					this.OncMassar_PrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName_Pr", DbType="NVarChar(50)")]
		public string firstName_Pr
		{
			get
			{
				return this._firstName_Pr;
			}
			set
			{
				if ((this._firstName_Pr != value))
				{
					this.OnfirstName_PrChanging(value);
					this.SendPropertyChanging();
					this._firstName_Pr = value;
					this.SendPropertyChanged("firstName_Pr");
					this.OnfirstName_PrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName_Pr", DbType="NVarChar(50)")]
		public string lastName_Pr
		{
			get
			{
				return this._lastName_Pr;
			}
			set
			{
				if ((this._lastName_Pr != value))
				{
					this.OnlastName_PrChanging(value);
					this.SendPropertyChanging();
					this._lastName_Pr = value;
					this.SendPropertyChanged("lastName_Pr");
					this.OnlastName_PrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[genre-Pr]", Storage="_genre_Pr", DbType="NVarChar(50)")]
		public string genre_Pr
		{
			get
			{
				return this._genre_Pr;
			}
			set
			{
				if ((this._genre_Pr != value))
				{
					this.Ongenre_PrChanging(value);
					this.SendPropertyChanging();
					this._genre_Pr = value;
					this.SendPropertyChanged("genre_Pr");
					this.Ongenre_PrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateNaiss_Pr", DbType="Date")]
		public System.Nullable<System.DateTime> dateNaiss_Pr
		{
			get
			{
				return this._dateNaiss_Pr;
			}
			set
			{
				if ((this._dateNaiss_Pr != value))
				{
					this.OndateNaiss_PrChanging(value);
					this.SendPropertyChanging();
					this._dateNaiss_Pr = value;
					this.SendPropertyChanged("dateNaiss_Pr");
					this.OndateNaiss_PrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lieuNaiss_Pr", DbType="NVarChar(100)")]
		public string lieuNaiss_Pr
		{
			get
			{
				return this._lieuNaiss_Pr;
			}
			set
			{
				if ((this._lieuNaiss_Pr != value))
				{
					this.OnlieuNaiss_PrChanging(value);
					this.SendPropertyChanging();
					this._lieuNaiss_Pr = value;
					this.SendPropertyChanged("lieuNaiss_Pr");
					this.OnlieuNaiss_PrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nOreder_Pr", DbType="Int")]
		public System.Nullable<int> nOreder_Pr
		{
			get
			{
				return this._nOreder_Pr;
			}
			set
			{
				if ((this._nOreder_Pr != value))
				{
					this.OnnOreder_PrChanging(value);
					this.SendPropertyChanging();
					this._nOreder_Pr = value;
					this.SendPropertyChanged("nOreder_Pr");
					this.OnnOreder_PrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classe_Pr", DbType="NVarChar(50)")]
		public string classe_Pr
		{
			get
			{
				return this._classe_Pr;
			}
			set
			{
				if ((this._classe_Pr != value))
				{
					this.Onclasse_PrChanging(value);
					this.SendPropertyChanging();
					this._classe_Pr = value;
					this.SendPropertyChanged("classe_Pr");
					this.Onclasse_PrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niveau_Pr", DbType="NVarChar(100)")]
		public string niveau_Pr
		{
			get
			{
				return this._niveau_Pr;
			}
			set
			{
				if ((this._niveau_Pr != value))
				{
					this.Onniveau_PrChanging(value);
					this.SendPropertyChanging();
					this._niveau_Pr = value;
					this.SendPropertyChanged("niveau_Pr");
					this.Onniveau_PrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[gresa-Pr]", Storage="_gresa_Pr", DbType="NVarChar(50)")]
		public string gresa_Pr
		{
			get
			{
				return this._gresa_Pr;
			}
			set
			{
				if ((this._gresa_Pr != value))
				{
					this.Ongresa_PrChanging(value);
					this.SendPropertyChanging();
					this._gresa_Pr = value;
					this.SendPropertyChanged("gresa_Pr");
					this.Ongresa_PrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_annescol_Pr", DbType="NVarChar(50)")]
		public string annescol_Pr
		{
			get
			{
				return this._annescol_Pr;
			}
			set
			{
				if ((this._annescol_Pr != value))
				{
					this.Onannescol_PrChanging(value);
					this.SendPropertyChanging();
					this._annescol_Pr = value;
					this.SendPropertyChanged("annescol_Pr");
					this.Onannescol_PrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentListUpdate")]
	public partial class StudentListUpdate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cMassar_Up;
		
		private string _firstName_Up;
		
		private string _lastName_Up;
		
		private string _genre_Up;
		
		private System.Nullable<System.DateTime> _dateNaiss_Up;
		
		private string _lieuNaiss_Up;
		
		private System.Nullable<int> _nOreder_Up;
		
		private string _classe_Up;
		
		private string _niveau_Up;
		
		private string _gresa_Up;
		
		private string _annescol_Up;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncMassar_UpChanging(string value);
    partial void OncMassar_UpChanged();
    partial void OnfirstName_UpChanging(string value);
    partial void OnfirstName_UpChanged();
    partial void OnlastName_UpChanging(string value);
    partial void OnlastName_UpChanged();
    partial void Ongenre_UpChanging(string value);
    partial void Ongenre_UpChanged();
    partial void OndateNaiss_UpChanging(System.Nullable<System.DateTime> value);
    partial void OndateNaiss_UpChanged();
    partial void OnlieuNaiss_UpChanging(string value);
    partial void OnlieuNaiss_UpChanged();
    partial void OnnOreder_UpChanging(System.Nullable<int> value);
    partial void OnnOreder_UpChanged();
    partial void Onclasse_UpChanging(string value);
    partial void Onclasse_UpChanged();
    partial void Onniveau_UpChanging(string value);
    partial void Onniveau_UpChanged();
    partial void Ongresa_UpChanging(string value);
    partial void Ongresa_UpChanged();
    partial void Onannescol_UpChanging(string value);
    partial void Onannescol_UpChanged();
    #endregion
		
		public StudentListUpdate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cMassar_Up", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cMassar_Up
		{
			get
			{
				return this._cMassar_Up;
			}
			set
			{
				if ((this._cMassar_Up != value))
				{
					this.OncMassar_UpChanging(value);
					this.SendPropertyChanging();
					this._cMassar_Up = value;
					this.SendPropertyChanged("cMassar_Up");
					this.OncMassar_UpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName_Up", DbType="NVarChar(50)")]
		public string firstName_Up
		{
			get
			{
				return this._firstName_Up;
			}
			set
			{
				if ((this._firstName_Up != value))
				{
					this.OnfirstName_UpChanging(value);
					this.SendPropertyChanging();
					this._firstName_Up = value;
					this.SendPropertyChanged("firstName_Up");
					this.OnfirstName_UpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName_Up", DbType="NVarChar(50)")]
		public string lastName_Up
		{
			get
			{
				return this._lastName_Up;
			}
			set
			{
				if ((this._lastName_Up != value))
				{
					this.OnlastName_UpChanging(value);
					this.SendPropertyChanging();
					this._lastName_Up = value;
					this.SendPropertyChanged("lastName_Up");
					this.OnlastName_UpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[genre-Up]", Storage="_genre_Up", DbType="NVarChar(50)")]
		public string genre_Up
		{
			get
			{
				return this._genre_Up;
			}
			set
			{
				if ((this._genre_Up != value))
				{
					this.Ongenre_UpChanging(value);
					this.SendPropertyChanging();
					this._genre_Up = value;
					this.SendPropertyChanged("genre_Up");
					this.Ongenre_UpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateNaiss_Up", DbType="Date")]
		public System.Nullable<System.DateTime> dateNaiss_Up
		{
			get
			{
				return this._dateNaiss_Up;
			}
			set
			{
				if ((this._dateNaiss_Up != value))
				{
					this.OndateNaiss_UpChanging(value);
					this.SendPropertyChanging();
					this._dateNaiss_Up = value;
					this.SendPropertyChanged("dateNaiss_Up");
					this.OndateNaiss_UpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lieuNaiss_Up", DbType="NVarChar(100)")]
		public string lieuNaiss_Up
		{
			get
			{
				return this._lieuNaiss_Up;
			}
			set
			{
				if ((this._lieuNaiss_Up != value))
				{
					this.OnlieuNaiss_UpChanging(value);
					this.SendPropertyChanging();
					this._lieuNaiss_Up = value;
					this.SendPropertyChanged("lieuNaiss_Up");
					this.OnlieuNaiss_UpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nOreder_Up", DbType="Int")]
		public System.Nullable<int> nOreder_Up
		{
			get
			{
				return this._nOreder_Up;
			}
			set
			{
				if ((this._nOreder_Up != value))
				{
					this.OnnOreder_UpChanging(value);
					this.SendPropertyChanging();
					this._nOreder_Up = value;
					this.SendPropertyChanged("nOreder_Up");
					this.OnnOreder_UpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classe_Up", DbType="NVarChar(50)")]
		public string classe_Up
		{
			get
			{
				return this._classe_Up;
			}
			set
			{
				if ((this._classe_Up != value))
				{
					this.Onclasse_UpChanging(value);
					this.SendPropertyChanging();
					this._classe_Up = value;
					this.SendPropertyChanged("classe_Up");
					this.Onclasse_UpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niveau_Up", DbType="NVarChar(100)")]
		public string niveau_Up
		{
			get
			{
				return this._niveau_Up;
			}
			set
			{
				if ((this._niveau_Up != value))
				{
					this.Onniveau_UpChanging(value);
					this.SendPropertyChanging();
					this._niveau_Up = value;
					this.SendPropertyChanged("niveau_Up");
					this.Onniveau_UpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[gresa-Up]", Storage="_gresa_Up", DbType="NVarChar(50)")]
		public string gresa_Up
		{
			get
			{
				return this._gresa_Up;
			}
			set
			{
				if ((this._gresa_Up != value))
				{
					this.Ongresa_UpChanging(value);
					this.SendPropertyChanging();
					this._gresa_Up = value;
					this.SendPropertyChanged("gresa_Up");
					this.Ongresa_UpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_annescol_Up", DbType="NVarChar(50)")]
		public string annescol_Up
		{
			get
			{
				return this._annescol_Up;
			}
			set
			{
				if ((this._annescol_Up != value))
				{
					this.Onannescol_UpChanging(value);
					this.SendPropertyChanging();
					this._annescol_Up = value;
					this.SendPropertyChanged("annescol_Up");
					this.Onannescol_UpChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Transaction]")]
	public partial class Transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _massar_trans_id_;
		
		private string _massar_trans_;
		
		private string _fname_trans_;
		
		private string _lname_trans_;
		
		private System.Nullable<System.DateTime> _dt_trans_;
		
		private string _typ_trans_;
		
		private string _etabOrig_trans_;
		
		private string _etabRecep_trans_;
		
		private string _direc_orig_recep_trans_;
		
		private System.Nullable<int> _part_entr_trans_;
		
		private string _niveau_trans_;
		
		private string _gresa_trans;
		
		private string _num_corres_trans;
		
		private System.Nullable<System.DateTime> _dt_corres_trans;
		
		private System.Nullable<bool> _req_send_trans;
		
		private System.Nullable<int> _nb_req_trans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmassar_trans_id_Changing(int value);
    partial void Onmassar_trans_id_Changed();
    partial void Onmassar_trans_Changing(string value);
    partial void Onmassar_trans_Changed();
    partial void Onfname_trans_Changing(string value);
    partial void Onfname_trans_Changed();
    partial void Onlname_trans_Changing(string value);
    partial void Onlname_trans_Changed();
    partial void Ondt_trans_Changing(System.Nullable<System.DateTime> value);
    partial void Ondt_trans_Changed();
    partial void Ontyp_trans_Changing(string value);
    partial void Ontyp_trans_Changed();
    partial void OnetabOrig_trans_Changing(string value);
    partial void OnetabOrig_trans_Changed();
    partial void OnetabRecep_trans_Changing(string value);
    partial void OnetabRecep_trans_Changed();
    partial void Ondirec_orig_recep_trans_Changing(string value);
    partial void Ondirec_orig_recep_trans_Changed();
    partial void Onpart_entr_trans_Changing(System.Nullable<int> value);
    partial void Onpart_entr_trans_Changed();
    partial void Onniveau_trans_Changing(string value);
    partial void Onniveau_trans_Changed();
    partial void Ongresa_transChanging(string value);
    partial void Ongresa_transChanged();
    partial void Onnum_corres_transChanging(string value);
    partial void Onnum_corres_transChanged();
    partial void Ondt_corres_transChanging(System.Nullable<System.DateTime> value);
    partial void Ondt_corres_transChanged();
    partial void Onreq_send_transChanging(System.Nullable<bool> value);
    partial void Onreq_send_transChanged();
    partial void Onnb_req_transChanging(System.Nullable<int> value);
    partial void Onnb_req_transChanged();
    #endregion
		
		public Transaction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[massar_trans_id ]", Storage="_massar_trans_id_", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int massar_trans_id_
		{
			get
			{
				return this._massar_trans_id_;
			}
			set
			{
				if ((this._massar_trans_id_ != value))
				{
					this.Onmassar_trans_id_Changing(value);
					this.SendPropertyChanging();
					this._massar_trans_id_ = value;
					this.SendPropertyChanged("massar_trans_id_");
					this.Onmassar_trans_id_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[massar_trans ]", Storage="_massar_trans_", DbType="NVarChar(50)")]
		public string massar_trans_
		{
			get
			{
				return this._massar_trans_;
			}
			set
			{
				if ((this._massar_trans_ != value))
				{
					this.Onmassar_trans_Changing(value);
					this.SendPropertyChanging();
					this._massar_trans_ = value;
					this.SendPropertyChanged("massar_trans_");
					this.Onmassar_trans_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[fname_trans ]", Storage="_fname_trans_", DbType="NVarChar(50)")]
		public string fname_trans_
		{
			get
			{
				return this._fname_trans_;
			}
			set
			{
				if ((this._fname_trans_ != value))
				{
					this.Onfname_trans_Changing(value);
					this.SendPropertyChanging();
					this._fname_trans_ = value;
					this.SendPropertyChanged("fname_trans_");
					this.Onfname_trans_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[lname_trans ]", Storage="_lname_trans_", DbType="NVarChar(50)")]
		public string lname_trans_
		{
			get
			{
				return this._lname_trans_;
			}
			set
			{
				if ((this._lname_trans_ != value))
				{
					this.Onlname_trans_Changing(value);
					this.SendPropertyChanging();
					this._lname_trans_ = value;
					this.SendPropertyChanged("lname_trans_");
					this.Onlname_trans_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[dt_trans ]", Storage="_dt_trans_", DbType="Date")]
		public System.Nullable<System.DateTime> dt_trans_
		{
			get
			{
				return this._dt_trans_;
			}
			set
			{
				if ((this._dt_trans_ != value))
				{
					this.Ondt_trans_Changing(value);
					this.SendPropertyChanging();
					this._dt_trans_ = value;
					this.SendPropertyChanged("dt_trans_");
					this.Ondt_trans_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[typ_trans ]", Storage="_typ_trans_", DbType="NVarChar(50)")]
		public string typ_trans_
		{
			get
			{
				return this._typ_trans_;
			}
			set
			{
				if ((this._typ_trans_ != value))
				{
					this.Ontyp_trans_Changing(value);
					this.SendPropertyChanging();
					this._typ_trans_ = value;
					this.SendPropertyChanged("typ_trans_");
					this.Ontyp_trans_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[etabOrig_trans ]", Storage="_etabOrig_trans_", DbType="NVarChar(100)")]
		public string etabOrig_trans_
		{
			get
			{
				return this._etabOrig_trans_;
			}
			set
			{
				if ((this._etabOrig_trans_ != value))
				{
					this.OnetabOrig_trans_Changing(value);
					this.SendPropertyChanging();
					this._etabOrig_trans_ = value;
					this.SendPropertyChanged("etabOrig_trans_");
					this.OnetabOrig_trans_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[etabRecep_trans ]", Storage="_etabRecep_trans_", DbType="NVarChar(100)")]
		public string etabRecep_trans_
		{
			get
			{
				return this._etabRecep_trans_;
			}
			set
			{
				if ((this._etabRecep_trans_ != value))
				{
					this.OnetabRecep_trans_Changing(value);
					this.SendPropertyChanging();
					this._etabRecep_trans_ = value;
					this.SendPropertyChanged("etabRecep_trans_");
					this.OnetabRecep_trans_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[direc_orig_recep_trans ]", Storage="_direc_orig_recep_trans_", DbType="NVarChar(100)")]
		public string direc_orig_recep_trans_
		{
			get
			{
				return this._direc_orig_recep_trans_;
			}
			set
			{
				if ((this._direc_orig_recep_trans_ != value))
				{
					this.Ondirec_orig_recep_trans_Changing(value);
					this.SendPropertyChanging();
					this._direc_orig_recep_trans_ = value;
					this.SendPropertyChanged("direc_orig_recep_trans_");
					this.Ondirec_orig_recep_trans_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[part_entr_trans ]", Storage="_part_entr_trans_", DbType="Int")]
		public System.Nullable<int> part_entr_trans_
		{
			get
			{
				return this._part_entr_trans_;
			}
			set
			{
				if ((this._part_entr_trans_ != value))
				{
					this.Onpart_entr_trans_Changing(value);
					this.SendPropertyChanging();
					this._part_entr_trans_ = value;
					this.SendPropertyChanged("part_entr_trans_");
					this.Onpart_entr_trans_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[niveau_trans ]", Storage="_niveau_trans_", DbType="NVarChar(50)")]
		public string niveau_trans_
		{
			get
			{
				return this._niveau_trans_;
			}
			set
			{
				if ((this._niveau_trans_ != value))
				{
					this.Onniveau_trans_Changing(value);
					this.SendPropertyChanging();
					this._niveau_trans_ = value;
					this.SendPropertyChanged("niveau_trans_");
					this.Onniveau_trans_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gresa_trans", DbType="NVarChar(50)")]
		public string gresa_trans
		{
			get
			{
				return this._gresa_trans;
			}
			set
			{
				if ((this._gresa_trans != value))
				{
					this.Ongresa_transChanging(value);
					this.SendPropertyChanging();
					this._gresa_trans = value;
					this.SendPropertyChanged("gresa_trans");
					this.Ongresa_transChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_corres_trans", DbType="NVarChar(50)")]
		public string num_corres_trans
		{
			get
			{
				return this._num_corres_trans;
			}
			set
			{
				if ((this._num_corres_trans != value))
				{
					this.Onnum_corres_transChanging(value);
					this.SendPropertyChanging();
					this._num_corres_trans = value;
					this.SendPropertyChanged("num_corres_trans");
					this.Onnum_corres_transChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_corres_trans", DbType="Date")]
		public System.Nullable<System.DateTime> dt_corres_trans
		{
			get
			{
				return this._dt_corres_trans;
			}
			set
			{
				if ((this._dt_corres_trans != value))
				{
					this.Ondt_corres_transChanging(value);
					this.SendPropertyChanging();
					this._dt_corres_trans = value;
					this.SendPropertyChanged("dt_corres_trans");
					this.Ondt_corres_transChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_req_send_trans", DbType="Bit")]
		public System.Nullable<bool> req_send_trans
		{
			get
			{
				return this._req_send_trans;
			}
			set
			{
				if ((this._req_send_trans != value))
				{
					this.Onreq_send_transChanging(value);
					this.SendPropertyChanging();
					this._req_send_trans = value;
					this.SendPropertyChanged("req_send_trans");
					this.Onreq_send_transChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nb_req_trans", DbType="Int")]
		public System.Nullable<int> nb_req_trans
		{
			get
			{
				return this._nb_req_trans;
			}
			set
			{
				if ((this._nb_req_trans != value))
				{
					this.Onnb_req_transChanging(value);
					this.SendPropertyChanging();
					this._nb_req_trans = value;
					this.SendPropertyChanged("nb_req_trans");
					this.Onnb_req_transChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
